#!/usr/bin/env bash

# Reset to local docker
eval $(docker-machine env -u)

# Update submodules (php, go ...)
git submodule update --recursive --remote

# Build All
docker-compose -f config/compose.common.json -f config/compose.development.json -p xmp build
if [ $? != 0 ]; then
    printf "\n\n BUILD FAIL \n\n"
    exit 1
fi
printf "\n\n"

docker system prune -f
printf "\n\n"
