#!/usr/bin/env bash

# Update submodules (php, go ...)
#git submodule update --recursive --remote
#if [ $? != 0 ]; then
#    printf "\n\n GIT FAIL \n\n"
#    exit 1
#fi

# Build All
docker-compose -f compose.json -p xmp build
if [ $? != 0 ]; then
    printf "\n\n BUILD FAIL \n\n"
    exit 1
fi
printf "\n\n"

#docker system prune -f
#printf "\n\n"
