#!/usr/bin/env bash

#docker-compose -f compose.json -p xmp down
#docker-compose -f compose.json -p xmp up --abort-on-container-exit

docker-compose -f compose.json -p xmp up -d sql
sleep 6
docker-compose -f compose.json -p xmp run --entrypoint 'php /app/yii migrate/up --interactive=0' --no-deps --rm php
docker-compose -f compose.json -p xmp up -d php
docker-compose -f compose.json -p xmp up -d go
docker-compose -f compose.json -p xmp up -d nginx
