#!/usr/bin/env bash

eval $(docker-machine env -u)
docker-compose -f ./config/compose.common.json -f ./config/compose.dev.json -p xmp down
docker-compose -f ./config/compose.common.json -f ./config/compose.dev.json -p xmp up --abort-on-container-exit
