app_name: acceptor

db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: linkit_test
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

server:
  rpc_port: 50313
  http_port: 50314

acceptor_client:
  dsn: :50313
  timeout: 10
