app_name: acceptor

db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: development
  user: local
  pass: local
  port: 5432
  host: sql
  ssl_mode: disable
  table_prefix: xmp_

server:
  port: 40400
